%mex torbeam.cpp ...
%    libtorbeam.a ...
%    -Lintellac5libs libsvml.a libifcore.a -lintlc libimf.a ...
%    -ldl

%mexcmd = sprintf('mex RABBIT.cpp -g -ldl -L%s -lRabbit',pwd);
%mexcmd = sprintf('mex RABBIT.cpp -g libRabbit.a -ldl');
%disp(mexcmd)
%eval(mexcmd)
if exist('RABBIT.mexa64','file')
  !rm RABBIT.mexa64
end


mex -v src/RABBIT.cpp -g -I./src -L./libs -I/home/weiland/rtccode/development/models/R2015a/algorithms/SCDrtRABBIT/../../../../libs/TCV_RT libRabbitMore.so ...
  -L/opt/intel/impi/5.1.1.109/lib64 -lmpicxx -lmpi  ...
  CXXFLAGS="$CXXFLAGS -fopenmp" ...
  LDFLAGS="$LDFLAGS -fopenmp" ...  
  -DVERBOSE

% mex -v src/RABBIT.cpp -g -I./src -L./libs -I/home/weiland/rtccode/development/models/R2015a/algorithms/SCDrtRABBIT/../../../../libs/TCV_RT libRabbitMore.so ...
%     libstdi.a ...   %Rainer Fischer library
%   nag_mk25/libnag_nag.a nag_mk25/libnag_mkl.a ...
%   nag_fl90/libnagfl90_nag.a ...  
%   -lpthread -lm -lifcore -lifport ...
%   -lc -ldl -lrt -liomp5 -lz -lcurl ...
%   -L/opt/intel/impi/5.1.1.109/lib64 -lmpicxx -lmpi -ldl -lm -lrt -lnsl -lutil -lm -ldl ...
%   CXXFLAGS="$CXXFLAGS -fopenmp" ...
%   LDFLAGS="$LDFLAGS -fopenmp" ...
%   CXXLINKFLAGS="$CXXLINKFLAGS ...
%   /lib64 /opt/intel/impi/5.1.1.109/lib64 ...
%   /home/weiland/fortran/rabbit/branches/lib ...
%   /home/weiland/fortran/rabbit/branches/lib/netcdf"...
%   -lifcore -lintlc  ...
%      libsvml.a libimf.a -DVERBOSE


% mex -v RABBIT.cpp -g libRabbit.a ...
%     libstdi.a ...   %Rainer Fischer library
%   nag_mk25/libnag_nag.a nag_mk25/libnag_mkl.a ...
%   nag_fl90/libnagfl90_nag.a ...  
%   -lpthread -lm -lifcore -lifport ...
%   -lc -ldl -lrt -liomp5 -lz -lcurl ...
%   CXXFLAGS="$CXXFLAGS -fopenmp" ...
%   LDFLAGS="$LDFLAGS -fopenmp" ...
%   CXXLINKFLAGS="$CXXLINKFLAGS ...
%   /lib64 /opt/intel/lib/intel64 ...
%   /home/weiland/fortran/rabbit/branches/lib ...
%   /home/weiland/fortran/rabbit/branches/lib/netcdf"...
%   -lifcore -lintlc  ...
%      libsvml.a libimf.a ...
%   netcdf_mpi/libnetcdff.a
  

%  mex rabbit.cpp ...
%      -Lintellac5libs -lifcore -lintlc  ...
%      libsvml.a libimf.a ...
%      -ldl

%  mex -g torbeam.cpp ...
%      libtorbeam.a ...
%      -lm -ldl 
